# Generated by Django 4.0.3 on 2022-03-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_old',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
