# Generated by Django 4.0.3 on 2022-03-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0002_products_price_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_period',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='link_to_picture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price_per_unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='store_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
