# Generated by Django 4.0.3 on 2022-03-27 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0004_products_date_time_grab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_time_grab',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
