# Generated by Django 4.0.3 on 2022-03-27 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0005_alter_products_date_time_grab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_time_grab',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 23, 1, 33, 314538), null=True),
        ),
    ]
