# Generated by Django 4.0.3 on 2022-03-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0007_alter_products_date_time_grab'),
    ]

    operations = [
        migrations.CreateModel(
            name='urls_barbora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='urls_rimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
