# Generated by Django 4.0.3 on 2022-03-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0011_rename_store_id_products_store_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
        migrations.RenameModel(
            old_name='urls',
            new_name='Url',
        ),
    ]
