# Generated by Django 4.0.3 on 2022-04-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0016_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_old',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='link_to_picture',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_per_unit', models.CharField(max_length=50, null=True)),
                ('discount_period', models.CharField(max_length=50, null=True)),
                ('date_time_grab', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marga.product')),
            ],
        ),
    ]
