# Generated by Django 4.0.3 on 2022-04-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0018_rename_prices_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_time_grab',
        ),
    ]
