# Generated by Django 4.0.3 on 2022-04-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0021_alter_price_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('price',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
