# Generated by Django 4.0.3 on 2022-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0022_alter_price_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
