# Generated by Django 4.0.3 on 2022-04-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0024_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='url_product',
            field=models.URLField(null=True),
        ),
    ]
