# Generated by Django 4.0.3 on 2022-04-20 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0026_rename_url_product_product_link_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marga.url'),
        ),
    ]
