# Generated by Django 4.0.4 on 2022-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0027_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
