# Generated by Django 4.0.4 on 2022-05-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marga', '0028_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link_to_product',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
