version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    container_name: djangotest_container
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
      