version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_container
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    container_name: rmscraper_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A rmscraper worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    build: .
    command: celery -A rmscraper beat -l INFO
    volumes:
      - .:/app
    depends_on:
    - db
    - app
    - redis
    - celery
    
volumes:
  data: