version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_container
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    container_name: rmscraper_container
    command: sh -c "uwsgi --socket mysite.sock --module rmscraper.wsgi --chmod-socket=666"
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A rmscraper worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    build: .
    command: celery -A rmscraper beat -l INFO
    volumes:
      - .:/app
    depends_on:
    - db
    - app
    - redis
    - celery
  smtp:
    image: namshi/smtp
    container_name: smtp_relay
    restart: always
    ports:
     - "25:25"
    environment:
     - RELAY_NETWORKS=:192.168.0.0/24
     - MAILNAME=marga
  nginx:
    image: nginx
    container_name: nginx_container
    restart: always
    ports:
     - "80:80"
    volumes:
      - .:/app
    command: sh -c "rm /etc/nginx/conf.d/* && cp /app/nginx/mysite_nginx.conf /etc/nginx/conf.d && nginx -g 'daemon off;'"
    
volumes:
  data: